apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudpilot-prod

resources:
- ../../base

namePrefix: prod-

commonLabels:
  environment: production

images:
- name: ghcr.io/moazzamhafeez1093/cloudpilot-api-gateway
  newName: ghcr.io/moazzamhafeez1093/cloudpilot-api-gateway
  newTag: 7d40854
- name: ghcr.io/moazzamhafeez1093/cloudpilot-notification-service
  newName: ghcr.io/moazzamhafeez1093/cloudpilot-notification-service
  newTag: 7d40854
- name: ghcr.io/moazzamhafeez1093/cloudpilot-product-service
  newName: ghcr.io/moazzamhafeez1093/cloudpilot-product-service
  newTag: 7d40854
- name: ghcr.io/moazzamhafeez1093/cloudpilot-user-service
  newName: ghcr.io/moazzamhafeez1093/cloudpilot-user-service
  newTag: 7d40854

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: api-gateway
    spec:
      replicas: 2
  target:
    kind: Deployment
    name: api-gateway
