apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-service-pvc
  labels:
    app: product-service
    project: cloudpilot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath